[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "CryWatchdog"
description = "CryWatchdog - Asset Management & Monitoring Tool"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
license-files = ["LICENSE*"]
authors = [{name = "kilazz"}]

dependencies = [
    "PySide6>=6.11.1",
    "PySide6-Fluent-Widgets>=1.11.3",
    "charset-normalizer>=3.4.9",
    "watchfiles>=1.2.0",
]

[dependency-groups]
dev = [
    "ruff",
    "pyright",
    "snakeviz",
    "py-spy",
    "tabulate2",
    "psutil",
    "tqdm",
]

[tool.uv]
default-groups = ["dev"]

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "UP",   # pyupgrade
    "SIM",  # flake8-simplify
    "RUF",  # Ruff-specific rules
    "PERF", # Perflint
    "FURB", # Refurb
    "LOG",  # flake8-logging
    "C4",   # flake8-comprehensions
    "TC",   # flake8-type-checking
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.14"
typeCheckingMode = "standard"
